-- 코드를 작성해주세요
-- cycle이 생기는 이상치가 없다고 가정
WITH RECURSIVE findGeneration(ID, PARENT_ID, GENERATION)  AS (
    SELECT ID, PARENT_ID, 1 as GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT t1.ID, t1.PARENT_ID, t2.GENERATION+1 
        FROM ECOLI_DATA as t1 JOIN findGeneration t2 ON t1.PARENT_ID = t2.ID
)

SELECT COUNT(g.ID) AS COUNT, g.GENERATION FROM findGeneration as g LEFT JOIN ECOLI_DATA as e on g.ID = e.PARENT_ID
WHERE e.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION ASC;